### ISSUE TITLE
cannot open source file "wiring.h"

### ISSUE THREAD

**Issue by ricreis394** [stonehippo/arduino-ethernet#2]
Hello,

I'm trying to use this library but it's saying that `wiring.h` doesn't exist

Using your example `PollingDHCP`:
```
C:\Users\user\Documents\Arduino\libraries\ArduinoEthernet\EthernetBonjour.cpp:29:13: fatal error: wiring.h: No such file or directory

Multiple libraries were found for "Ethernet.h"
    #include <wiring.h>

 Used: C:\Users\user\Documents\Arduino\libraries\Ethernet
             ^~~~~~~~~~

 Not used: C:\Program Files (x86)\Arduino\libraries\Ethernet
compilation terminated.

exit status 1
Error compiling for board Arduino Mega or Mega 2560.
```

any tip?

**Comment by stonehippo** [comment]
@ricreis394 this library is _ancient_ and hasn’t been updated in quite a while. You’re getting that compilation error because the code relies on pre-Arduino 1.x core libraries, including wiring.h and socket.h, both of which were removed for the AVR core 10 years ago.

I’ll take a look at see if it’s possible to get these compiling again, though I don’t have an Arduino Ethernet shield any longer, so I’m not entirely sure how I’ll be able to test them fully. I suspect it’s going to be more lift than I can do right now, and that this repo should be archived in favor of some other solution.

**Comment by stonehippo** [comment]
This repo is getting deprecated, so I’ve closed this issue as a won’t fix.
